test
ee9/ingipro1 pull request #1
Opened 2017-07-15 10:28 UTC by ee9

2017-07-15 11:10 UTC, mar4uk requested changes

2017-07-15 11:10 UTC, mar4uk commented on 3510.js
> +    return Object.keys(obj);
Элементы этого массива строки. 
Нужно привести их к числам.

2017-07-15 11:10 UTC, mar4uk commented on 3623.js
> +var res = arr.reduce(function(previousValue, currentValue, index, array) {
внутри функции не используешь переменные index, array, поэтому их можно не передавать

2017-07-15 11:10 UTC, mar4uk commented on 3736.js
> +        if(!checkLetter(str[i])) {
давай сделаем проверку сразу всей строки регулярным выражением

2017-07-15 11:10 UTC, mar4uk commented on 3902.js
> +alert ( sum(1)(2)(3)); // => 6
для вызовов sum(1)(2) и sum(1)(2)(3) будет ошибка

2017-07-20 13:47 UTC, closed without merging

2017-07-20 13:47 UTC, ee9 commented
.