Ex5
ee9/ingipro1 pull request #7
Opened 2017-07-19 21:44 UTC by ee9

2017-07-19 22:04 UTC, mar4uk requested changes

2017-07-19 22:04 UTC, mar4uk commented on 5p2.js
> +    let index = str.indexOf(before);
index нигде не используешь

2017-07-19 22:04 UTC, mar4uk commented on 5p2.js
> +    return result;
можно сразу вернуть `return str.replace(before,after);` - код на пару строк короче

2017-07-20 12:33 UTC, ee9 commented
а, вот тут нужно)
@mar4uk

2017-07-20 18:53 UTC, mar4uk commented on 5p2.js
> +    const result = "";
не используешь далее эту переменную

2017-07-20 18:54 UTC, mar4uk approved these changes

2017-07-20 18:54 UTC, mar4uk commented
👍

2017-07-20 18:54 UTC, closed without merging